---

- include: ../redhat/selinux.yml
  when: not ansible_selinux
 
- name: Add the official sensu repository
  copy:
    src='{{ sensu_yum_repo_file }}'
    dest='/etc/yum.repos.d'
    owner=root
    group=root 
